### PR TITLE
fix(collectibles): sanitize user-facing error messages 

### LINKED ISSUE #84: Error message returns internal details
### What version are you using?
Latest

### What did you do?
curl -s -X POST \
  "https://freighter-backend-v2.stellar.org/api/v1/collectibles?network=FUTURENET" \
  -H "Content-Type: application/json" \
  -d '{"owner":"GAIH3ULLFQ4DGSECF2AR555KZ4KNDGEKN4AFI4SU2M7B43MGK3QJZNSR"}' \
  | jq '.data.collections[].error.error_message'

returns
{
  "error": {
    "error_message": "dial tcp <IP>: connect: connection refused"
  }
}

### What did you expect to see?
A user facing error message

### What did you see instead?
internal details

### PR DESCRIPTION
**Pull request by aristidesstaffieri**
Closes #84 

What
Sanitize and use end user facing error messages for collectibles route.

Why
Internal RPC/transport errors (e.g. "dial tcp <IP>: connect: connection refused") were being returned in the error_message field of collectibles responses, leaking infrastructure details to clients. Replace these with generic user-facing messages while logging the underlying error server-side for debugging, and add a regression test that verifies no internal details leak through.

### CODE REVIEW

File: internal/api/handlers/collectibles.go [hunk 1]
```diff
@@ -255,9 +269,10 @@ func (h *CollectiblesHandler) fetchMeridianPayCollectibles(
 			// Check context before starting work
 			select {
 			case <-ctx.Done():
+				logger.ErrorWithContext(ctx, fmt.Sprintf("context done before fetching meridian pay collectible %s: %v", contract, ctx.Err()))
 				results[i] = CollectionResult{
 					Error: &CollectionError{
-						ErrorMessage:      ctx.Err().Error(),
+						ErrorMessage:      msgRequestTimeout,
 						CollectionAddress: contract,
```
[the remark this answers is not in the document]
Comment (aristidesstaffieri) [reply internal/api/handlers/collectibles.go:275]: used a more generic message for both cases in d5e28496fcf69e4560279b805e07a21563be282a

File: internal/api/handlers/collectibles_test.go [hunk 2]
```diff
@@ -258,10 +259,55 @@ func TestGetCollectibles_WithMeridianPayAddresses(t *testing.T) {
...
 		assert.NotNil(t, col.Error)
-		assert.Contains(t, col.Error.ErrorMessage, "no collectibles fetched")
+		assert.Equal(t, msgNoCollectiblesFetched, col.Error.ErrorMessage)
 	}
 }
 
+// Regression test for https://github.com/stellar/freighter-backend-v2/issues/84
+// Internal RPC errors (containing IPs, hostnames, low-level transport details) must
+// not be exposed in the user-facing error_message field.
+func TestGetCollectibles_DoesNotLeakInternalErrorDetails(t *testing.T) {
```
Comment (JakeUrban) [inline internal/api/handlers/collectibles_test.go]: I'm not sure if adding this test adds value if we're also testing that the current implementation functions as intended (i.e. the correct error messages are displayed). This test will never fail when the other tests pass.

**Review by JakeUrban — APPROVED** [review]
LGTM aside from one comment.

File: internal/api/handlers/collectibles_test.go (hunk 2 above)
Comment (aristidesstaffieri) [reply internal/api/handlers/collectibles_test.go]: yeah fair enough it is pretty redundant, deleted in dad28c5749a57f6a93a1a577812553d4111175c4

**Review by piyalbasu — APPROVED** [review]
